### ISSUE TITLE
Contribuições ao projeto

### ISSUE THREAD

**Issue by Viniberaldo** [RuanSDias/Clean_Energy#24]
Olá, como estão?

Existe intenção em prosseguir com o projeto de vocês? Estou procurando um projeto open source relacionado à energia ou eficiência energética para contribuir.

Até mais.

**Comment by RuanSDias** [comment]
Olá Vinícius,

O projeto Clean Energy não foi um projeto de energia, mas sim de
desenvolvimento web. Todas as informações nele contido são fictícias e tem
somente o intuito acadêmico.

Att, Ruan

Em sáb, 27 de ago de 2022 09:55, Vinícius A. B. ***@***.***>
escreveu:

**Comment by Viniberaldo** [comment]
Compreendo. Obrigado pela atenção.
